language: python
stages:
  - linting
  - install
  - push
  - deploy

jobs:
  include:
    # Deploy to PyPi if all tests pass and change was done on master.
    - stage: deploy
      name: "Deploy to PyPi"
      install: pip install -U pip setuptools wheel
      script: skip
      deploy: &pypi
        provider: pypi
        user: "$PYPIUSER"
        password: "$PYPIKEY"
        on:
          tags: true